# Generated by Django 5.2.5 on 2025-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
