# Generated by Django 5.2.5 on 2025-08-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adults',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='child',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_num',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
